//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_location.Model.Res {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projet_location.Model.Res.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Acceuil {
            get {
                return ResourceManager.GetString("Acceuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building address.
        /// </summary>
        public static string AdresseImmeuble {
            get {
                return ResourceManager.GetString("AdresseImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location address.
        /// </summary>
        public static string AdresseLocation {
            get {
                return ResourceManager.GetString("AdresseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string AdresseProprietaire {
            get {
                return ResourceManager.GetString("AdresseProprietaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display all lodgment .
        /// </summary>
        public static string AfficherAppartement {
            get {
                return ResourceManager.GetString("AfficherAppartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a lodgment .
        /// </summary>
        public static string AjoutAppartement {
            get {
                return ResourceManager.GetString("AjoutAppartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a lease.
        /// </summary>
        public static string AjouterUnBail {
            get {
                return ResourceManager.GetString("AjouterUnBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a lodgment.
        /// </summary>
        public static string AjouterUneLocation {
            get {
                return ResourceManager.GetString("AjouterUneLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a building.
        /// </summary>
        public static string AjouterUnImmeuble {
            get {
                return ResourceManager.GetString("AjouterUnImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a tenant.
        /// </summary>
        public static string AjouterUnLocataire {
            get {
                return ResourceManager.GetString("AjouterUnLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family allowances.
        /// </summary>
        public static string AllocFamilliale {
            get {
                return ResourceManager.GetString("AllocFamilliale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Housing allowances.
        /// </summary>
        public static string AllocLogement {
            get {
                return ResourceManager.GetString("AllocLogement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm payment.
        /// </summary>
        public static string Apayer {
            get {
                return ResourceManager.GetString("Apayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Before 1949.
        /// </summary>
        public static string Avant1949 {
            get {
                return ResourceManager.GetString("Avant1949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lease.
        /// </summary>
        public static string Bail {
            get {
                return ResourceManager.GetString("Bail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rental lease.
        /// </summary>
        public static string BailLocation {
            get {
                return ResourceManager.GetString("BailLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        public static string Chemin {
            get {
                return ResourceManager.GetString("Chemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a building.
        /// </summary>
        public static string ChoisirImmeuble {
            get {
                return ResourceManager.GetString("ChoisirImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a tenant.
        /// </summary>
        public static string ChoisirLocataire {
            get {
                return ResourceManager.GetString("ChoisirLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a rental.
        /// </summary>
        public static string ChoisirLocation {
            get {
                return ResourceManager.GetString("ChoisirLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postcode.
        /// </summary>
        public static string CodePostalLocation {
            get {
                return ResourceManager.GetString("CodePostalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collective.
        /// </summary>
        public static string Collectif {
            get {
                return ResourceManager.GetString("Collectif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collective.
        /// </summary>
        public static string Collective {
            get {
                return ResourceManager.GetString("Collective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional address.
        /// </summary>
        public static string ComplementAdresseLocation {
            get {
                return ResourceManager.GetString("ComplementAdresseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My account.
        /// </summary>
        public static string Compte {
            get {
                return ResourceManager.GetString("Compte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Co-owner.
        /// </summary>
        public static string Copropriete {
            get {
                return ResourceManager.GetString("Copropriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building date.
        /// </summary>
        public static string DateConstruction {
            get {
                return ResourceManager.GetString("DateConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lease start date.
        /// </summary>
        public static string DateDebutBail {
            get {
                return ResourceManager.GetString("DateDebutBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Birthdate.
        /// </summary>
        public static string DateNaissance {
            get {
                return ResourceManager.GetString("DateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment date.
        /// </summary>
        public static string DatePayement {
            get {
                return ResourceManager.GetString("DatePayement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adjustment date.
        /// </summary>
        public static string DateRevalorisation {
            get {
                return ResourceManager.GetString("DateRevalorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature date.
        /// </summary>
        public static string DateSignature {
            get {
                return ResourceManager.GetString("DateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tax declaration.
        /// </summary>
        public static string DeclarationFiscale {
            get {
                return ResourceManager.GetString("DeclarationFiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnection.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Since 2005.
        /// </summary>
        public static string Depuis2005 {
            get {
                return ResourceManager.GetString("Depuis2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Designation of the tenant.
        /// </summary>
        public static string DesignationLocataire {
            get {
                return ResourceManager.GetString("DesignationLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment diagram.
        /// </summary>
        public static string Diagramme {
            get {
                return ResourceManager.GetString("Diagramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration : .
        /// </summary>
        public static string Duree {
            get {
                return ResourceManager.GetString("Duree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lease duration.
        /// </summary>
        public static string DureeBail {
            get {
                return ResourceManager.GetString("DureeBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Between 1949 and 1974.
        /// </summary>
        public static string Entre19491974 {
            get {
                return ResourceManager.GetString("Entre19491974", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Between 1975 and 1989.
        /// </summary>
        public static string Entre19751989 {
            get {
                return ResourceManager.GetString("Entre19751989", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Between 1990 and 2005.
        /// </summary>
        public static string Entre19902005 {
            get {
                return ResourceManager.GetString("Entre19902005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid address.
        /// </summary>
        public static string ErreurAdresse {
            get {
                return ResourceManager.GetString("ErreurAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid postcode.
        /// </summary>
        public static string ErreurCodePostal {
            get {
                return ResourceManager.GetString("ErreurCodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid additional address.
        /// </summary>
        public static string ErreurComplementAdresse {
            get {
                return ResourceManager.GetString("ErreurComplementAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email or/and password incorrect.
        /// </summary>
        public static string ErreurConnexion {
            get {
                return ResourceManager.GetString("ErreurConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid date.
        /// </summary>
        public static string ErreurDate {
            get {
                return ResourceManager.GetString("ErreurDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid payment date.
        /// </summary>
        public static string ErreurDatePayement {
            get {
                return ResourceManager.GetString("ErreurDatePayement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid adjustment date.
        /// </summary>
        public static string ErreurDateRevalorisation {
            get {
                return ResourceManager.GetString("ErreurDateRevalorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid tenant.
        /// </summary>
        public static string ErreurLocataire {
            get {
                return ResourceManager.GetString("ErreurLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid rental.
        /// </summary>
        public static string ErreurLocation {
            get {
                return ResourceManager.GetString("ErreurLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid name.
        /// </summary>
        public static string ErreurNom {
            get {
                return ResourceManager.GetString("ErreurNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Country.
        /// </summary>
        public static string ErreurPays {
            get {
                return ResourceManager.GetString("ErreurPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid city.
        /// </summary>
        public static string ErreurVille {
            get {
                return ResourceManager.GetString("ErreurVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It it in a building?.
        /// </summary>
        public static string EstDansUnImmeuble {
            get {
                return ResourceManager.GetString("EstDansUnImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is it a building?.
        /// </summary>
        public static string EstImmeuble {
            get {
                return ResourceManager.GetString("EstImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate an inventory file.
        /// </summary>
        public static string EtatdesLieux {
            get {
                return ResourceManager.GetString("EtatdesLieux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory.
        /// </summary>
        public static string EtatsdesLieux {
            get {
                return ResourceManager.GetString("EtatsdesLieux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finances.
        /// </summary>
        public static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total winnings = .
        /// </summary>
        public static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate a pdf for this lease.
        /// </summary>
        public static string GenererPdfBail {
            get {
                return ResourceManager.GetString("GenererPdfBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lease management.
        /// </summary>
        public static string GestionBail {
            get {
                return ResourceManager.GetString("GestionBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person who haven&apos;t paid.
        /// </summary>
        public static string Impayer {
            get {
                return ResourceManager.GetString("Impayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Individual.
        /// </summary>
        public static string Individuel {
            get {
                return ResourceManager.GetString("Individuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Individual.
        /// </summary>
        public static string Individuelle {
            get {
                return ResourceManager.GetString("Individuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign up.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which one.
        /// </summary>
        public static string Lequel {
            get {
                return ResourceManager.GetString("Lequel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rental.
        /// </summary>
        public static string Locataire {
            get {
                return ResourceManager.GetString("Locataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tenant.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Residences.
        /// </summary>
        public static string Logements {
            get {
                return ResourceManager.GetString("Logements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rent.
        /// </summary>
        public static string Loyer {
            get {
                return ResourceManager.GetString("Loyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rent excluding charges : .
        /// </summary>
        public static string LoyerHC {
            get {
                return ResourceManager.GetString("LoyerHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Has the rent been paid?.
        /// </summary>
        public static string LoyerPaye {
            get {
                return ResourceManager.GetString("LoyerPaye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email address.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string MDPProprietaire {
            get {
                return ResourceManager.GetString("MDPProprietaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification.
        /// </summary>
        public static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        public static string ModifierItem {
            get {
                return ResourceManager.GetString("ModifierItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a rental.
        /// </summary>
        public static string ModifierUneLocation {
            get {
                return ResourceManager.GetString("ModifierUneLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a tenant.
        /// </summary>
        public static string ModifierUnLocataire {
            get {
                return ResourceManager.GetString("ModifierUnLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mono owner.
        /// </summary>
        public static string Monopropriete {
            get {
                return ResourceManager.GetString("Monopropriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charges.
        /// </summary>
        public static string MontantCharge {
            get {
                return ResourceManager.GetString("MontantCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rent excluding charges.
        /// </summary>
        public static string MontantLoyerHorsCharges {
            get {
                return ResourceManager.GetString("MontantLoyerHorsCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationality.
        /// </summary>
        public static string Nationalite {
            get {
                return ResourceManager.GetString("Nationalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beds&apos; number.
        /// </summary>
        public static string NbCouchages {
            get {
                return ResourceManager.GetString("NbCouchages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of dependants.
        /// </summary>
        public static string NbPersonneACharge {
            get {
                return ResourceManager.GetString("NbPersonneACharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of main rooms.
        /// </summary>
        public static string NbPiecesPrincipales {
            get {
                return ResourceManager.GetString("NbPiecesPrincipales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lease name.
        /// </summary>
        public static string NomBail {
            get {
                return ResourceManager.GetString("NomBail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the building.
        /// </summary>
        public static string NomImmeuble {
            get {
                return ResourceManager.GetString("NomImmeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tenant name.
        /// </summary>
        public static string NomLocataire {
            get {
                return ResourceManager.GetString("NomLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location name .
        /// </summary>
        public static string NomLocation {
            get {
                return ResourceManager.GetString("NomLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purpose of the contrat.
        /// </summary>
        public static string ObjetContrat {
            get {
                return ResourceManager.GetString("ObjetContrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Parcourir {
            get {
                return ResourceManager.GetString("Parcourir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have an account ?.
        /// </summary>
        public static string PasDeCompte {
            get {
                return ResourceManager.GetString("PasDeCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment.
        /// </summary>
        public static string Payement {
            get {
                return ResourceManager.GetString("Payement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person having paid.
        /// </summary>
        public static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        public static string PaysLocation {
            get {
                return ResourceManager.GetString("PaysLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legal entity.
        /// </summary>
        public static string PersonneMorale {
            get {
                return ResourceManager.GetString("PersonneMorale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Natural person.
        /// </summary>
        public static string PersonnePhysique {
            get {
                return ResourceManager.GetString("PersonnePhysique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string PrenomLocataire {
            get {
                return ResourceManager.GetString("PrenomLocataire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occupation.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment reset.
        /// </summary>
        public static string RemettreZero {
            get {
                return ResourceManager.GetString("RemettreZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External income.
        /// </summary>
        public static string RevenusExterieur {
            get {
                return ResourceManager.GetString("RevenusExterieur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly salary net .
        /// </summary>
        public static string SalaireMensuelNet {
            get {
                return ResourceManager.GetString("SalaireMensuelNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Sinscrire {
            get {
                return ResourceManager.GetString("Sinscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Family situation .
        /// </summary>
        public static string SituationFamilliale {
            get {
                return ResourceManager.GetString("SituationFamilliale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Floor space (m²).
        /// </summary>
        public static string SurfaceHabitable {
            get {
                return ResourceManager.GetString("SurfaceHabitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tenants table.
        /// </summary>
        public static string TableauDesLocataires {
            get {
                return ResourceManager.GetString("TableauDesLocataires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rentals table.
        /// </summary>
        public static string TableauDesLocations {
            get {
                return ResourceManager.GetString("TableauDesLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title of the pdf.
        /// </summary>
        public static string TitrePdf {
            get {
                return ResourceManager.GetString("TitrePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heater type.
        /// </summary>
        public static string TypeChauffage {
            get {
                return ResourceManager.GetString("TypeChauffage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agreement type.
        /// </summary>
        public static string TypeDeContrat {
            get {
                return ResourceManager.GetString("TypeDeContrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hot water type.
        /// </summary>
        public static string TypeEauChaude {
            get {
                return ResourceManager.GetString("TypeEauChaude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of housing.
        /// </summary>
        public static string TypeHabitat {
            get {
                return ResourceManager.GetString("TypeHabitat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of rental.
        /// </summary>
        public static string TypeLocation {
            get {
                return ResourceManager.GetString("TypeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of person.
        /// </summary>
        public static string TypePersonne {
            get {
                return ResourceManager.GetString("TypePersonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property type.
        /// </summary>
        public static string TypePropriete {
            get {
                return ResourceManager.GetString("TypePropriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a building date.
        /// </summary>
        public static string VeuillezChoisirDateConstruction {
            get {
                return ResourceManager.GetString("VeuillezChoisirDateConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        public static string VilleLocation {
            get {
                return ResourceManager.GetString("VilleLocation", resourceCulture);
            }
        }
    }
}
